# Generated by Django 3.1 on 2020-11-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=15, null=True, verbose_name='手机'),
        ),
    ]
